name: Deploy to BGA Studio

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upload via SFTP
      env:
        BGA_USER: ${{ secrets.BGA_USERNAME }}
        BGA_PASS: ${{ secrets.BGA_PASSWORD }}
      run: |
        sshpass -p "$BGA_PASS" sftp -o StrictHostKeyChecking=no -o Port=22 $BGA_USER@studio.boardgamearena.com <<EOF
        cd /var/tournoi/projects/lichocar/
        mput -r *
        quit
        EOF
